# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{akamai}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jay Zeschin"]
  s.date = %q{2010-02-05}
  s.description = %q{Simple library for interacting with Akamai NetStorage and EdgeSuite caches}
  s.email = %q{jay.zeschin@factorylabs.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "akamai.gemspec",
     "lib/akamai.rb",
     "test/helper.rb",
     "test/test_akamai.rb"
  ]
  s.homepage = %q{http://github.com/jayzes/akamai}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple library for interacting with Akamai NetStorage and EdgeSuite caches}
  s.test_files = [
    "test/helper.rb",
     "test/test_akamai.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<soap4r>, [">= 0"])
    else
      s.add_dependency(%q<soap4r>, [">= 0"])
    end
  else
    s.add_dependency(%q<soap4r>, [">= 0"])
  end
end

